name: Docker Build and Push

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/my_app:latest .
        working-directory: .

      - name: Tag Docker image
        run: docker tag your-dockerhub-username/my_app:latest your-dockerhub-username/my_app:${{ github.sha }}

      - name: Push Docker image
        run: docker push your-dockerhub-username/my_app
